import '../shared/models/entry.dart';

final List<Entry> mockEntries = [
  Entry(
    id: 'casa',
    headword: 'casa',
    definition: 'Edifício onde as pessoas vivem',
    exampleSentence: 'A minha casa é grande e confortável.',
    flags: [1, 2],
    createdAt: DateTime.now().subtract(const Duration(days: 30)),
    updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    updatedBy: 'theunissens@kiekies.net',
  ),
  Entry(
    id: 'correr',
    headword: 'correr',
    definition: 'Mover-se rapidamente usando os pés',
    exampleSentence: 'Ele gosta de correr todas as manhãs.',
    flags: [],
    createdAt: DateTime.now().subtract(const Duration(days: 180)),
    updatedAt: DateTime.now().subtract(const Duration(days: 60)),
    updatedBy: 'theunissens@kiekies.net',
  ),
  Entry(
    id: 'bonito',
    headword: 'bonito',
    definition: 'Que tem beleza, que agrada à vista',
    exampleSentence: 'O vestido é muito bonito.',
    flags: [3],
    createdAt: DateTime.now().subtract(const Duration(days: 365)),
    updatedAt: DateTime.now().subtract(const Duration(days: 200)),
    updatedBy: 'theunissens@kiekies.net',
  ),
  Entry(
    id: 'rapidamente',
    headword: 'rapidamente',
    definition: 'De modo rápido, com velocidade',
    exampleSentence: 'Ele terminou o trabalho rapidamente.',
    flags: [1, 2, 3],
    createdAt: DateTime.now().subtract(const Duration(days: 500)),
    updatedAt: DateTime.now().subtract(const Duration(days: 400)),
    updatedBy: 'theunissens@kiekies.net',
  ),
  Entry(
    id: 'ele',
    headword: 'ele',
    definition: 'Pronome pessoal da terceira pessoa do singular',
    exampleSentence: 'Ele está estudando para o exame.',
    flags: [],
    createdAt: DateTime.now().subtract(const Duration(days: 700)),
    updatedAt: DateTime.now().subtract(const Duration(days: 600)),
    updatedBy: 'theunissens@kiekies.net',
  ),
  Entry(
    id: 'primeiro',
    headword: 'primeiro',
    definition: 'Que ocupa a posição inicial em uma sequência',
    exampleSentence: 'Ele foi o primeiro a chegar.',
    flags: [2],
    createdAt: DateTime.now().subtract(const Duration(days: 730)),
    updatedAt: DateTime.now().subtract(const Duration(days: 700)),
    updatedBy: 'theunissens@kiekies.net',
  ),
  Entry(
    id: 'com',
    headword: 'com',
    definition: 'Indica companhia, instrumento ou modo',
    exampleSentence: 'Vou viajar com meus amigos.',
    flags: [],
    createdAt: DateTime.now().subtract(const Duration(days: 365)),
    updatedAt: DateTime.now().subtract(const Duration(days: 100)),
    updatedBy: 'theunissens@kiekies.net',
  ),
  Entry(
    id: 'mas',
    headword: 'mas',
    definition: 'Indica oposição ou contraste',
    exampleSentence: 'Quero ir, mas estou cansado.',
    flags: [1],
    createdAt: DateTime.now().subtract(const Duration(days: 400)),
    updatedAt: DateTime.now().subtract(const Duration(days: 50)),
    updatedBy: 'theunissens@kiekies.net',
  ),
  Entry(
    id: 'ai',
    headword: 'ai',
    definition: 'Expressão de dor ou surpresa',
    exampleSentence: 'Ai! Meu dedo!',
    flags: [3],
    createdAt: DateTime.now().subtract(const Duration(days: 200)),
    updatedAt: DateTime.now().subtract(const Duration(days: 10)),
    updatedBy: 'theunissens@kiekies.net',
  ),
];
